### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Kecoey/week12#1]
It looks like the final criterion isn't yet complete:

> NOT display any links to unauthorized actions to anonymous visitors (such as links to create a new record, edit a record, or delete a record)

Even when not logged in, I see these Edit and Destroy links. Can you update this please?

**Comment by Kecoey** [comment]
Sorry about that, I didn't think about after you make a new "guess the number". It should be fixed now.

**Comment by chrisvfritz** [comment]
Just a tiny bit too far in the other direction. I do still want to see the Show link when I'm not signed in, since it doesn't allow any changes to the database.

**Comment by Kecoey** [comment]
Ok and then that also allowed them to see the edit link from the show page, so I removed that.

**Comment by chrisvfritz** [comment]
:+1: Excellent!
